"""
Goncik-tech - Inteligentny serwer z zapisem danych
Serwuje stronę na http://localhost:8000 i zapisuje zmiany z panelu admina do pliku js/data.js
"""
import http.server
import socketserver
import json
import os
import sys
import re
from datetime import datetime
from urllib.parse import urlparse, parse_qs
from pathlib import Path

PORT = 8000
PROJECT_DIR = Path(__file__).parent.resolve()
DATA_FILE = PROJECT_DIR / "js" / "data.js"


class GoncikHandler(http.server.SimpleHTTPRequestHandler):
    """Handler HTTP z endpointem /api/save do zapisywania danych."""

    # Wyciszenie domyślnych logów — logujemy ładnie
    def log_message(self, format, *args):
        sys.stderr.write(
            f"[{datetime.now().strftime('%H:%M:%S')}] {self.address_string()} - {format % args}\n"
        )

    def end_headers(self):
        # Prosty CORS dla bezpieczeństwa lokalnego
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        super().end_headers()

    def do_OPTIONS(self):
        self.send_response(204)
        self.end_headers()

    def do_POST(self):
        parsed = urlparse(self.path)
        if parsed.path == "/api/save":
            self.handle_save()
        elif parsed.path == "/api/reset":
            self.handle_reset()
        else:
            self.send_error(404, "Unknown endpoint")

    def do_GET(self):
        parsed = urlparse(self.path)
        if parsed.path == "/api/status":
            self.handle_status()
        else:
            super().do_GET()

    # ----------------------------
    # Endpoints
    # ----------------------------
    def handle_status(self):
        payload = {
            "status": "ok",
            "data_file": str(DATA_FILE),
            "data_exists": DATA_FILE.exists(),
            "data_size": DATA_FILE.stat().st_size if DATA_FILE.exists() else 0,
            "server_time": datetime.now().isoformat(timespec="seconds"),
        }
        self.send_json(200, payload)

    def handle_save(self):
        try:
            length = int(self.headers.get("Content-Length", "0"))
            raw = self.rfile.read(length).decode("utf-8")
            data = json.loads(raw)
        except Exception as e:
            return self.send_json(400, {"ok": False, "error": f"Invalid JSON: {e}"})

        scripts = data.get("scripts", [])
        tutorials = data.get("tutorials", [])
        news = data.get("news", [])

        # Podstawowa walidacja — każdy item musi mieć id
        for label, arr in (("scripts", scripts), ("tutorials", tutorials), ("news", news)):
            for item in arr:
                if "id" not in item:
                    return self.send_json(400, {"ok": False, "error": f"Item in {label} missing id"})

        try:
            content = render_data_js(scripts, tutorials, news)
            DATA_FILE.write_text(content, encoding="utf-8")
            print(
                f"[SAVE] scripts={len(scripts)} tutorials={len(tutorials)} news={len(news)} -> {DATA_FILE.name}"
            )
            return self.send_json(200, {
                "ok": True,
                "saved": {"scripts": len(scripts), "tutorials": len(tutorials), "news": len(news)},
                "path": str(DATA_FILE),
            })
        except Exception as e:
            return self.send_json(500, {"ok": False, "error": str(e)})

    def handle_reset(self):
        """Przywraca plik data.js do wbudowanej kopii zapasowej (jeśli istnieje)."""
        backup = PROJECT_DIR / "js" / "data.backup.js"
        if not backup.exists():
            return self.send_json(404, {"ok": False, "error": "No backup file"})
        DATA_FILE.write_text(backup.read_text(encoding="utf-8"), encoding="utf-8")
        return self.send_json(200, {"ok": True})

    def send_json(self, code, payload):
        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


def render_data_js(scripts, tutorials, news):
    """
    Generuje zawartość pliku data.js w czytelnym formacie.
    Plik ma udawać strukturę: window.data = { scripts, tutorials, news }
    """
    header = (
        "// ============================================\n"
        "// DATABASE - Scripts, Tutorials, News\n"
        "// Auto-generated by server_api.py\n"
        + f"// Last update: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        + "// ============================================\n\n"
    )

    def dump(name, arr):
        return f"const {name} = " + json.dumps(arr, ensure_ascii=False, indent=4) + ";\n\n"

    body = (
        header
        + dump("scripts", scripts)
        + dump("tutorials", tutorials)
        + dump("news", news)
        + "// Expose globally so app.js can read it without imports\n"
        + "window.data = { scripts: scripts, tutorials: tutorials, news: news };\n"
    )
    return body


def make_backup():
    """Tworzy backup pliku data.js przy pierwszym uruchomieniu."""
    backup = PROJECT_DIR / "js" / "data.backup.js"
    if DATA_FILE.exists() and not backup.exists():
        try:
            backup.write_text(DATA_FILE.read_text(encoding="utf-8"), encoding="utf-8")
            print(f"[BOOT] Backup created -> {backup.name}")
        except Exception as e:
            print(f"[BOOT] Could not create backup: {e}")


def main():
    make_backup()

    # Zmiana katalogu roboczego na katalog projektu
    os.chdir(PROJECT_DIR)

    # Pozwól na ponowne uruchomienie serwera szybko (bez TIME_WAIT)
    socketserver.TCPServer.allow_reuse_address = True

    print("=" * 56)
    print("  GONCIK-TECH - Serwer z zapisem danych")
    print("=" * 56)
    print(f"  Projekt : {PROJECT_DIR}")
    print(f"  Adres   : http://localhost:{PORT}")
    print(f"  Plik DB : {DATA_FILE}")
    print("  Naciśnij Ctrl+C aby zatrzymać serwer")
    print("=" * 56)

    try:
        with socketserver.TCPServer(("", PORT), GoncikHandler) as httpd:
            httpd.serve_forever()
    except KeyboardInterrupt:
        print("\n[STOP] Serwer zatrzymany.")
    except OSError as e:
        print(f"[ERROR] Nie można uruchomić serwera na porcie {PORT}: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
